[package]
name = "pipsearch"
version = "0.1.0"
authors = ["Timm Behner <timm.behner@fkie.fraunhofer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pip-search"
path = "src/main.rs"
test = false


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
anyhow = "*"
scraper = "*"
chrono = "0.4"
lazy_static = "1.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
